name = "yueplush-techblog"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"

[pages]
pages_build_output_dir = ".vercel/output/static"
